services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - es-network

networks:
  es-network:
    driver: bridge
